version: "2"
plugins:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
  eslint:
    enabled: true
    channel: "eslint-3"
    checks:
      import/no-unresolved:
        enabled: false
      import/extensions:
        enabled: false
    config:
      extensions:
      - .js
      - .jsx
  scss-lint:
    enabled: true
exclude_patterns:
- node_modules/
- config/ # build configuration
- scripts/ # build & utility scripts
- src/__mocks__/ # test objects
- src/Constants/PropTypes.js # shape definitions
- "src/**/*.test.js" # unit tests
- "src/**/*.test.jsx" # unit tests
